### ISSUE TITLE
Set step execution result

### ISSUE THREAD

**Issue by MarcoCaballero** [kinow/testlink-java-api#100]
Hello,

I have been trying for a long time to find a way to establish the result of the execution of the steps of a test. 

I have seen that in the python API, based on the rpc xml as well, **there is already a method for it.** 

Searching in the original source of testlink I have found the following: 
[FEATURE TICKET 7313: API XMLRPC - possibility to set the step-test result](https://github.com/TestLinkOpenSourceTRMS/testlink-code/commit/f8a25e414c33e93a5fcb6d1c2c1c68e1186b1cf1).
**It seems that is already possible to report the result of each step** by xmlrpc.class.php or xmlrpc.php.

 Is it possible with the java api? 

Thank you in advance.

**Comment by Gemasoft** [comment]
Hello, I'm facing the same issue did you get it resolved?

**Comment by kinow** [comment]
Hi @MarcoCaballero thanks for adding the link to the implementation in PHP. Looks like they added an extra param to the reportTCResult.

I suspect we are just missing that parameter somewhere around here https://github.com/kinow/testlink-java-api/blob/4db4a30e48c321825ebcf91c7152965213187e23/src/main/java/br/eti/kinoshita/testlinkjavaapi/TestCaseService.java#L581

I don't have a working development environment to implement, test, and prepare a pull request/commit for that. But if anyone submits one, I'd be happy to review/merge/release it 🎉

**Comment by luisavina** [comment]
Hi Bruno, @kinow 
Could you help me to add this functionality to the API, please? As we disccused before I really need to send the step results from Java (Eclipse) directly to Testlink. 

I really appreciate your help. 

Thank you!

**Comment by kinow** [comment]
Unfortunately I don't have the development environment, nor am using TestLink at the moment.

This would require someone knowin Java and XML/REST API's to go through both code bases and change the code.

**Comment by kinow** [comment]
Merged pull request with fix for this issue. Closing. Released in 1.9.16-3
