### ISSUE TITLE
Get Test Case assigned to user info

### ISSUE THREAD

**Issue by nvhnam95** [kinow/testlink-java-api#101]
Hi, thank you for the API, its very useful.
But I need to get assign information, the information we like is similar to the table when user click "Test cases assigned to me" label on Testlink home. 
We tried to get all test cases and then get the lastest execute status, but there are no assigned date. Can you show me a way to get there such information?

The image to illustrate the table I want to get:

![6067d3315e8a729741cabfc147f0e5fd31eefe286de0265fa4 pimgpsh_fullsize_distr](https://user-images.githubusercontent.com/23403381/33926850-5d81d114-e012-11e7-8a7a-e9693b4eb503.jpg)

**Comment by kinow** [comment]
Thanks for reporting it and for the kind words.

It depends first on the PHP API availability. We are a simple facade for the PHP API. And then it depends on me finding spare time to update the code and release it, or someone else submitting some code.

Pull requests welcome :)

**Comment by nvhnam95** [comment]
Thanks for replying. 
I understand now, thank you.
