### ISSUE TITLE
How to get generated TestLink reports ?

### ISSUE THREAD

**Issue by karanshah10** [kinow/testlink-java-api#103]
Try to fetch generated TestLink report for particular Build  .

**Comment by kinow** [comment]
Hi @karanshah10 , if there is a method in the PHP API, we can implement that method in this API too. But you would first have to find the method in the PHP API, then check if it exists in this Java project.

If there is a method in PHP, and it is missing in this Java API, feel free to report an issue asking for that method to be implemented.

If there is no such method, then you would have to implement that logic in your own application. This API is simply a facade to the PHP API, and we avoid adding extra feature/methods.
