### ISSUE TITLE
reportTCResult - test case steps results are ignored / not updated

### ISSUE THREAD

**Issue by schwarcu** [kinow/testlink-java-api#112]
```
List<TestCaseStep> steps = testCase.getSteps();
            List<TestCaseStepResult> stepsResults = new ArrayList<>();
            for (TestCaseStep step : steps) {
                TestCaseStepResult stepResult = new TestCaseStepResult();
                stepResult.setNumber(step.getNumber());
                stepResult.setResult(ExecutionStatus.PASSED);
                stepResult.setNotes("Note " + step.getId());
                stepsResults.add(stepResult);
            }
```

Simple code to make all steps passed. No matter what I pass as parameter steps results are never updated in TestLink.

**Comment by schwarcu** [comment]
This seems to be TestLink issue, reported as http://mantis.testlink.org/view.php?id=8492

**Comment by schwarcu** [comment]
TestLink ticket has been closed by fman, the only man that seems to be "alive" in TestLink. Can you please verify that this client is up to date?

**Comment by kinow** [comment]
Not using TestLink or the java API at the moment, and busy with $work. So am only mergin pull requests and releasing to maven central.

**Comment by ranashahan** [comment]
@kinow you need to debug it properly, i run through the complete thread  and code and does not find anything which is blocking our code to communicate with Testlink API but somehow steps are not updated into testlink. (might i be missing something).

Complete execution data is followed (example with multiple steps OR only 1 step)
`executionData	HashMap<K,V>  (id=397)	
{
testcaseid=17, 
notes=testing test case has been executed automatically from , 
testplanid=15, 
buildid=2, 
platformid=2, 
steps=[
TestCaseStepResult [number=1, result=p, notes=Note 1], 
TestCaseStepResult [number=2, result=p, notes=Note 2]
], 
 OR
[TestCaseStepResult [number=1, result=p, notes=Note RanaMansoor]],

customfields=null, 
platformname=ENV01, 
buildname=Example Build001, 
bugid=null, 
guess=true, 
testcaseexternalid=1, 
overwrite=false, 
status=p
}`

Regards,
Rana Mansoor

**Comment by kinow** [comment]
>@kinow you need to debug it properly,

Hi @ranashahan, see my previous comment. Not using it right now, besides occasionally downloading code, spinning a Docker container and testing the API to release a new version. So unlikely to debug it now, sorry.

>i run through the complete thread and code and does not find anything which is blocking our code to communicate with Testlink API 

That's good to hear! I can't imagine what would cause that on our side, besides either a bug in the code, or an issue in one of the libraries used by the API.

>but somehow steps are not updated into testlink. (might i be missing something).

My guess would be that the request is missing something that TestLink is expecting. Or maybe the request has some parameter that TestLink is not happy with.

When I had a TestLink instance, and issues like this occurred, I normally debugged in the PHP side first (xdebug + eclipse), taking notes of why the response was not what I expected. Normally I would also copy the XML request/response for a test later. And then try to fix it.

Happy to merge pull requests for this issue, but won't have much time to do a thorough analysis now. Sorry.

Thanks for taking your time to analyze and report your findings @ranashahan , and sorry if you still have this issue or similar @schwarcu 

Cheers
Bruno

**Comment by ranashahan** [comment]
hi @kinow 
I know you are not using but you have to do little bit work if we stuck issue like this. please spare some time and fix it.

> My guess would be that the request is missing something that TestLink is expecting. Or maybe the request has some parameter that TestLink is not happy with.

Here is the problem request submitted successfully and i can see my notes been updated in Testlink perfectly but only skip test steps result & its notes.

> When I had a TestLink instance, and issues like this occurred, I normally debugged in the PHP side first (xdebug + eclipse), taking notes of why the response was not what I expected. Normally I would also copy the XML request/response for a test later. And then try to fix it.
Waiting.... . . .  .  .  .   .   .   .

**Comment by kinow** [comment]
Hi @ranashahan

>  you have to do little bit work if we stuck issue like this. please spare some time and fix it.

Sorry, but that is not correct. This is an open source project, maintained as volunteer work.

Demanding developers to stop their personal or professional lives to fix open source issues is considered bad etiquette.

Search for open source bad users, and you will find links like this.

https://news.ycombinator.com/item?id=12000746

I appreciate your contributions, and apologize for taking so long to fix issues. But that's all I can do now.

Bruno

**Comment by kinow** [comment]
Turns out the request was not correct. The steps part was not being serialized. Changed to a map, as in other methods, and it correctly went through.

Enabled the option to display the latest information for steps in TestLink, and here's what the code

```java
        Execution execution = api.getLastExecutionResult(testPlanId, testCaseId, externalCaseId, (Integer) null,
                (String) null, (Integer) buildId, (String) null, (Integer) null);
        System.out.println(execution);
        System.out.println("---");
        List<TestCaseStepResult> stepsResults = new ArrayList<>();
        for (TestCaseStep step : testCase.getSteps()) {
            TestCaseStepResult stepResult = new TestCaseStepResult();
            stepResult.setNumber(step.getNumber());
            stepResult.setResult(ExecutionStatus.PASSED);
            stepResult.setNotes("Note " + step.getId());
            stepsResults.add(stepResult);
        }
        ReportTCResultResponse response = api.reportTCResult(testCaseId, null, testPlanId,
                ExecutionStatus.BLOCKED, stepsResults,
                buildId, null, null, null, null, null, null,
                null, null, null, null, null);
        System.out.println(response);
```

produced:

![image](https://user-images.githubusercontent.com/304786/56486457-c71bd580-652b-11e9-86e4-e09769d98e0a.png)

**Comment by VTristan** [comment]
Hello !
I have the same problem.

I followed the code,
TestLink updates fine except for the steps.

Even when I click to see the 'print view':
![tesltLink1](https://user-images.githubusercontent.com/53631092/93327729-09c60800-f81b-11ea-931c-01f53ec92c7c.png)
![testLink2](https://user-images.githubusercontent.com/53631092/93328074-83f68c80-f81b-11ea-9491-0cb16b25eeb1.png)
![testLink3](https://user-images.githubusercontent.com/53631092/93328444-01220180-f81c-11ea-889e-a3fbae749fb3.png)

What do you mean:
"Enabled the option to display the latest information for the steps in TestLink, and here's what the code"?

How to activate this option, it is not enough to put the type of execution in "automated"?

(My version is 1.9.20-0)

Regards,

Tristan Vlasic

**Comment by kinow** [comment]
I've re-opened it as otherwise I would forget about it @VTristan 

Thanks for looking at existing issues. Closing again as I **think** it's a TestLink **Jenkins** plugin issue for your case (sorry the confusion).

I've written a reply to your e-mail with more comments :+1:
