### ISSUE TITLE
getTestCaseCustomFieldExecutionValue is outdated

### ISSUE THREAD

**Issue by schwarcu** [kinow/testlink-java-api#113]
![testlinkapiclientoutdated](https://user-images.githubusercontent.com/31127747/49367884-99093680-f6ed-11e8-8fdb-629541f18e5a.PNG)

API Client throws exception:
`br.eti.kinoshita.testlinkjavaapi.util.TestLinkAPIException: No test plan id provided.`

when attempting to get test execution custom field value. I compared the source code with TestLink api and it seems that required parameter **_testplanid_** is not passed to the TestLink API.

**Comment by kinow** [comment]
Pull requests welcome!

Unfortunately don't have an environment to test/develop, and not using TestLink at the moment.

Cheers

**Comment by ranashahan** [comment]
hmm... look interesting to me, let see what i can do with that issue, although it has already been create so much noise #59 in past..

**Comment by ranashahan** [comment]
@schwarcu i fixed exactly which shown into attached image (added testplan_id into getTestCaseCustomFieldExecutionValue), please verify it first against my  pull request and if it works then we can merge it. 

Regards,
Rana Mansoor

**Comment by schwarcu** [comment]
@ranashahan  finally someone come with a rescue haha. Thanks a lot, I will test this change on my testlink instance and will let you know!

**Comment by kinow** [comment]
Looks like this one was fixed in the pr #117 but never closed. Mea culpa, updating it.
