### ISSUE TITLE
Need to get testcases assigned for a build and the platforms added

### ISSUE THREAD

**Issue by sivasan8** [kinow/testlink-java-api#116]
I need to get the testcases that are assigned for a build and platforms added for the respective build. How can i get it.

**Comment by kinow** [comment]
Pull requests welcome! :grin:

**Comment by sivasan8** [comment]
kinow,

can you please update me the xmlrpc call to get testcases assigned to any specific build so that i can pull your source and make the changes accordingly.

**Comment by kinow** [comment]
Sorry @sivasan8 , no bandwidth at the moment to work on this fix. I'm working on other projects and don't have spare time right now.

**Comment by kinow** [comment]
@sivasan8 just re-read your issue description, and it sounds more like you are asking about a feature that should be in the TestLink PHP API. If you have a method there, then you should find an equivalent method here in the Java API. If not, please open an issue specifying which method you need. Then either I or another developer will prepare a pull request for this feature.

I am not using TestLink at the moment, so I'm afraid you will have to read the docs of the TL PHP API to see what you'd need 👍
