### ISSUE TITLE
Build release date and closed date both fields are not handled

### ISSUE THREAD

**Issue by ranashahan** [kinow/testlink-java-api#118]
@kinow 
I suspect build release & closed dates both fields are not handled by this API and when i saw code its written 

> // TBD: add release date and closed on date to Build entity

Is there any specific reason you didn't cater these field?

**Comment by kinow** [comment]
No special reason @ranashahan . I built the API mainly to use in the Jenkins TestLink plugin (which I built for a project sponsored by a previous company). Probably I simply didn't need those fields for the plugin to work.

**Comment by ranashahan** [comment]
@kinow Worked this weekend and added both options, please approve PR if it does not break anything.

**Comment by kinow** [comment]
Done @ranashahan ! Release done in a few hours. Thanks a ton!
