### ISSUE TITLE
java.lang.NoSuchMethodError: 'void org.apache.xmlrpc.client.XmlRpcClientConfigImpl.setUserAgent(java.lang.String)'

### ISSUE THREAD

**Issue by poncoe** [kinow/testlink-java-api#152]
Hi Mr Kinow,

i dont know what happen, but i got this problem when using your library, i trying to use diffrent version of xmlrpc-client or commons-configuration2, but not solve my problem, and showing error logs `java.lang.NoSuchMethodError: 'void org.apache.xmlrpc.client.XmlRpcClientConfigImpl.setUserAgent(java.lang.String)'`

full logs : 
`Reason:
java.lang.NoSuchMethodError: 'void org.apache.xmlrpc.client.XmlRpcClientConfigImpl.setUserAgent(java.lang.String)'
	at br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.createXmlRpcClientConfiguration(TestLinkAPI.java:270)
	at br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.<init>(TestLinkAPI.java:138)`

i'm using your latest version library testlink, thanks.

**Comment by kinow** [comment]
Hi @poncoe 

Looks like this `setUserAgent` call, here, https://github.com/kinow/testlink-java-api/blob/b3bd0ca1c2c43fa79bedab9e53c76433597a7345/src/main/java/br/eti/kinoshita/testlinkjavaapi/TestLinkAPI.java#L270, is not available in the version of the XML RPC client you have.

The latest TestLink Java API has 3.1.3 https://github.com/kinow/testlink-java-api/blob/b3bd0ca1c2c43fa79bedab9e53c76433597a7345/pom.xml#L76, if your version is newer, then we will have to see if they have a similar method to change the user agent, and adjust the TL API Code, and update our `pom.xml` to use that version of the XML RPC API.

Can you share the version of XML RPC you are using?

Cheers

**Comment by poncoe** [comment]
Hi Mr @kinow 

i using xmlrpc ver 3.1 and now use ver 3.1.3 its works, thankyou very much.
