### ISSUE TITLE
Method getTestPlanCustomFieldDesignValue() missed

### ISSUE THREAD

**Issue by OvejaNegra** [kinow/testlink-java-api#28]
I'm upgrading the version of Testlink Java API bla bla bla... (I mentioned a couple of hours ago) and notice that the method "getTestPlanCustomFieldDesignValue()" is missing. It's got the following signature (from TestLinkAPI.java):

public CustomField getTestPlanCustomFieldDesignValue(String customfieldname, Integer tprojectid, Integer testplanid) throws TestLinkAPIException {
      //compiled code
      throw new RuntimeException("Compiled Code");
   }

Please take a look.

Regards again,
Ricardo.

**Comment by kinow** [comment]
Quite old issue, looks like it was fixed later and I just never closed it. Sorry.

![image](https://user-images.githubusercontent.com/304786/56486601-43161d80-652c-11e9-8f06-8fa3a3072102.png)

Closing now.
