### ISSUE TITLE
java.lang.ClassCastException when connecting from jenkins to testlink

### ISSUE THREAD

**Issue by feixiang8418** [kinow/testlink-java-api#31]
Sorry but I don´t knokw whether this is the proper place to post this issue...

OS: ubuntu 12.03
DB: MySql
PHP: 5.4.22

And the maven dependency is:

<dependency>
      <groupId>br.eti.kinoshita</groupId>
      <artifactId>testlink-java-api</artifactId>
      <version>1.9.6-1</version>
      <scope>compile</scope>
</dependency>

When we connect from Jenkins to Testlink through testlink java API, we met the
following problem:

09:57:13 java.lang.ClassCastException: java.util.HashMap cannot be cast to
[Ljava.lang.Object;
09:57:13        at
br.eti.kinoshita.testlinkjavaapi.util.Util.castToArray(Util.java:566)
09:57:13        at
br.eti.kinoshita.testlinkjavaapi.TestCaseService.getTestCaseIDByName(TestCaseService.java:392)
09:57:13        at
br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.getTestCaseIDByName(TestLinkAPI.java:840)
09:57:13        at
de.zalando.test_framework.cucumber.reporter.TestLinkReporter.commitTestResults(TestLinkReporter.java:159)
09:57:13        at
de.zalando.test_framework.cucumber.reporter.TestLinkReporter.reportToTestLink(TestLinkReporter.java:151)
09:57:13        at
de.zalando.test_framework.cucumber.reporter.TestLinkReporter.scenario(TestLinkReporter.java:66)
09:57:13        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:57:13        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
09:57:13        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:57:13        at java.lang.reflect.Method.invoke(Method.java:601)
09:57:13        at cucumber.runtime.Utils$1.call(Utils.java:35)
09:57:13        at cucumber.runtime.Timeout.timeout(Timeout.java:12)
09:57:13        at cucumber.runtime.Utils.invoke(Utils.java:31)
09:57:13        at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:151)
09:57:13        at $Proxy18.scenario(Unknown Source)
09:57:13        at
cucumber.runtime.junit.JUnitReporter.scenario(JUnitReporter.java:161)
09:57:13        at gherkin.formatter.model.Scenario.replay(Scenario.java:18)
09:57:13        at cucumber.runtime.model.StepContainer.format(StepContainer.java:31)
09:57:13        at
cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:39)
09:57:13        at
cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:83)
09:57:13        at
cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
09:57:13        at
cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
09:57:13        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
09:57:13        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
09:57:13        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
09:57:13        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
09:57:13        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
09:57:13        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
09:57:13        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
09:57:13        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:82)
09:57:13        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:41)
09:57:13        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
09:57:13        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
09:57:13        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
09:57:13        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
09:57:13        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
09:57:13        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
09:57:13        at cucumber.api.junit.Cucumber.run(Cucumber.java:87)
09:57:13        at
org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
09:57:13        at
org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
09:57:13        at
org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
09:57:13        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:57:13        at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
09:57:13        at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:57:13        at java.lang.reflect.Method.invoke(Method.java:601)
09:57:13        at
org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
09:57:13        at
org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
09:57:13        at
org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
09:57:13        at
org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:113)
09:57:13        at
org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by kinow** [comment]
Looks like I forgot to close this ticket. PR: https://github.com/kinow/testlink-java-api/pull/34
