### ISSUE TITLE
Exception in getTestCaseIDByName

### ISSUE THREAD

**Issue by mummana** [kinow/testlink-java-api#40]
i have testcase under a testsuite the name of the testcase under testsuite is "100-1:check whether integration is done with webdriver" when i  call this methods as 
api.getTestCaseIDByName("100-1:check whether integration is done with webdriver");
its throws an exception as "Cannot find matching test case. No testcase exists with the name provided!, code=5030}" Please help me

**Comment by kinow** [comment]
Seems to be working with latest code against 1.9.19 (don't think this method has changed much in the past releases).

![image](https://user-images.githubusercontent.com/304786/56093411-882ec400-5f1c-11e9-8d41-491c9c0a46f5.png)
