### ISSUE TITLE
Ability to get Requirements linkings and properties

### ISSUE THREAD

**Issue by basraouik** [kinow/testlink-java-api#44]
The API should provide ways to get Requirements linkings to Test Cases (for example, it should give the Map of requirements linked to TC-1) and their properties (for example, Req Status, Coverage, Relations ...)

**Comment by FranclisJunior** [comment]
+1

**Comment by kamal951** [comment]
+1

**Comment by kinow** [comment]
@basraouik agree with it, but when you say "The API", remember this Java API is just a mere facade to the PHP XML-RPC API. In case you know of a method (even if it's in the JSON API, we can start working on the JSON client too) feel free to update the ticket, as that would make it easier to check how hard it would be to implement it.

**Comment by kinow** [comment]
Closing as this needs to be discussed in the PHP backend. See methods related to requirements in the latest (1.9.19) release:

- uploadRequirementSpecificationAttachment
- uploadRequirementAttachment
- assignRequirements
- getRequirementCustomFieldDesignValue
- getRequirements

Once the PHP API gets a new method, we can add the Java new call.
