### ISSUE TITLE
WebDriver - Testlink integration problem - Error verifying developer key

### ISSUE THREAD

**Issue by mzaldivar** [kinow/testlink-java-api#45]
Hi Mr. Kinoshita, 
I'm trying to add a new feature to my testframework (made with selenium webdriver), the integration with testlink. But somehow, when I try to run the basic API (testlink api v1.9.8) example, I'm getting the following error:

br.eti.kinoshita.testlinkjavaapi.util.TestLinkAPIE xception: Error verifying developer key: Failed to read server's response: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderE xception: unable to find valid certification path to requested target
at br.eti.kinoshita.testlinkjavaapi.MiscService.check DevKey(MiscService.java:64)
at br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.<init >(TestLinkAPI.java:145)

Here's the code:

package com.testframework.integrations.testlink;

import java.net.MalformedURLException;
import java.net.URL;

import br.eti.kinoshita.testlinkjavaapi.TestLinkAPI;
import br.eti.kinoshita.testlinkjavaapi.util.TestLinkAPIException;

import com.utec.testframework.driverwrapper.Driver;

public class TestLinkInstance 
{
public TestLinkInstance(Driver driver)
{
String url = "https://<my_server>/lib/api/xmlrpc/v1/xmlrpc.php";
String devKey = "<my_personal_api_id>";

TestLinkAPI api = null;
URL testlinkURL = null;

try {
testlinkURL = new URL(url);
} catch ( MalformedURLException mue ) {
mue.printStackTrace( System.err );
driver.kill();
}

try {
api = new TestLinkAPI(testlinkURL, devKey);
} catch( TestLinkAPIException te) {
te.printStackTrace( System.err );
driver.kill();
}

System.out.println(api.ping());

}
}

I investigated the testlink api source code, and I found that it throws the exception in the method named executeXmlRpcCall(String methodName, Map<String, Object> executionData), located in the following class: BaseService.java.

Hope you can give me a hand on this.

Thank you very much!

**Comment by kinow** [comment]
Closing as I believe the original issue has been fixed. @mzaldivar, feel free to open another issue in case you still need help with that other method.

Cheers,
Bruno
