### ISSUE TITLE
How to Convert Octet-Stream to String while Using clientGetTestCaseAttachments

### ISSUE THREAD

**Issue by ChaitanyaQA** [kinow/testlink-java-api#46]
Hi Bruno,

We have Uploaded a text file which contains some few Test Steps in TestLink, while we are trying to Read the Attached file using clientGetTestCaseAttachments we are getting Octet Stream Data, Could you please help me out, how to convert that Octet Stream into String..

Thanks
Chaitanya

**Comment by kinow** [comment]
Hey Chaitanya,

Sorry for the delay. You have to use a Base64 decoder. I have always used Apache Commons IO [Base64](https://commons.apache.org/proper/commons-codec/apidocs/org/apache/commons/codec/binary/Base64.html) for that, but there may be a simpler way in the JDK which I'm not aware.

Hope that helps, closing the issue but feel free to reply to this issue.
Bruno
