### ISSUE TITLE
Relevant Bugs

### ISSUE THREAD

**Issue by dokaspar** [kinow/testlink-java-api#48]
My Testlink project is configured with JIRA issue tracking support, so we can link executed test cases to JIRA issues. The Testlink GUI shows linked JIRA issues for a selected test execution.

Is it possible to retrieve this list of issue also through the Java Testlink API? I searched a lot but did not find any method to achieve this...

Greetings,
Dominik

**Comment by kinow** [comment]
@dokaspar maybe getTestCaseBugs? Looking at 1.9.14, this method has the following comment in the PHP code:

```
  * Returns all bugs linked to a particular testcase on a test plan.
  * If there are no filter criteria regarding platform and build,
  * result will be get WITHOUT checking for a particular platform and build.
```
