### ISSUE TITLE
getSteps() for Test Case returns empty array

### ISSUE THREAD

**Issue by gavk34** [kinow/testlink-java-api#49]
Even though the test case in Test Link has steps the Java API method always returns an empty array.

Using 1.9.3-4.jar against 1.9.3 TestLink

Any help greatly appreciated. Thanks

**Comment by mainframer** [comment]
" TestCase[] cases = api.getTestCasesForTestSuite(testSuite.getId(), true, null);" returns an empty array of steps.

If you set detail, then it will return steps.
 "
TestCaseDetails detail = TestCaseDetails.FULL;
 TestCase[] cases = api.getTestCasesForTestSuite(testSuite.getId(), true, detail);
"
