### ISSUE TITLE
getTestCasesForTestPlan() returns mostly null values

### ISSUE THREAD

**Issue by dokaspar** [kinow/testlink-java-api#5]
I'm using the testlink-java-api-1.9.4-0 and trying to retrieve all TestCases for a given testplanID:

``` java
TestCase[] cases = cliconn.getTestCasesForTestPlan(testplanID,
    null, null, null, null, null, null, null, null,
    null, TestCaseDetails.FULL);
```

However, whatever TestCaseDetails I pick (e.g., FULL, SIMPLE, or even null), I get the same results with 'name' and 'testSuiteId' and many other values equals null, always something like this:

_TestCase [id=70219, name=null, testSuiteId=null, testProjectId=null, authorLogin=null, summary=null, steps=[], preconditions=null, testImportance=null, executionType=1, executionOrder=0, order=null, internalId=null, fullExternalId=35, checkDuplicatedName=null, actionOnDuplicatedName=null, versionId=70220, version=1, parentId=null, customFields=[], executionStatus=p]_

Is this a bug or am I missing something here?

**Comment by nlazouzi** [comment]
not sure i understand the fix for this...i'm having the same problem.
i'm using 'br.eti.kinoshita:testlink-java-api:1.9.14-0'.  and when i get the test cases back i get >> here is an example of one case that has test steps, a summary, keywords but yet returns nulls...
>>>>>>>>>>>>>>>TestCase [id=163952, name=Client1ToThing2, testSuiteId=null, testProjectId=null, authorLogin=null, summary=null, steps=[], preconditions=null, testCaseStatus=7, testImportance=null, executionType=2, executionOrder=10000, order=null, internalId=null, fullExternalId=AWS-1030, checkDuplicatedName=null, actionOnDuplicatedName=null, versionId=163953, version=1, parentId=null, customFields=[], executionStatus=n, platform=Platform [id=0, name=, notes=null], featureId=63739, keywords= null]
><<<<<<<<<<<<
