### ISSUE TITLE
Report test case execution duration

### ISSUE THREAD

**Issue by gunnee** [kinow/testlink-java-api#55]
The test case execution duration cannot be added when reporting a test case result (see br.eti.kinoshita.testlinkjavaapi.TestCaseService.reportTCResult). It currently has to be inserted manually.

**Comment by ashahariharan** [comment]
I want to use the testlink plugin for Jenkins to update the execution duration of test cases. Is this supported

**Comment by kinow** [comment]
@ashahariharan don't think so. Not yet at least.

**Comment by kinow** [comment]
Ack @gunnee, just confirmed that we can add this feature with the next release.

Looking at TestLink source code: https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/testlink_1_9/lib/api/xmlrpc/v1/xmlrpc.class.php

I can see the execution duration optional field.

And we are not passing this parameter from the Java API: https://github.com/kinow/testlink-java-api/blob/master/src/main/java/br/eti/kinoshita/testlinkjavaapi/TestCaseService.java#L574

Seems easy to fix :-) should be included in the next release.

**Comment by kinow** [comment]
Ack @gunnee, just confirmed that we can add this feature with the next release.

Looking at TestLink source code: https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/testlink_1_9/lib/api/xmlrpc/v1/xmlrpc.class.php

I can see the execution duration optional field.

And we are not passing this parameter from the Java API: https://github.com/kinow/testlink-java-api/blob/master/src/main/java/br/eti/kinoshita/testlinkjavaapi/TestCaseService.java#L574

Seems easy to fix :-) should be included in the next release.

**Comment by uoolyn** [comment]
In the latest version 1.9.16-1 , still cannot be added  test case execution duration.
Thank you for fixing it

**Comment by uoolyn** [comment]
@kinow  In the latest version 1.9.16-1 , still cannot be added  test case execution duration.
Thank you for fixing it

**Comment by kinow** [comment]
Done, and adding `user` and `timestamp` parameters as well. Tested with 1.9.19.

```java
        ReportTCResultResponse response = api.reportTCResult(testCaseId, null, testPlanId, ExecutionStatus.BLOCKED,
                Collections.emptyList(), buildId, null, "Done!", 12, false, null, null, null, null, false, "admin", null);
```

Which returned:

```
ReportTCResultResponse [operation=reportTCResult, overwrite=null, status=null, message=Success!, executionId=2, bugIDStatus=null, customFieldStatus=null]
```

And the Web interface of TestLink also displays the correct values were used.

![image](https://user-images.githubusercontent.com/304786/56477615-cb2fff00-64fb-11e9-8fdf-fb0f7242195a.png)
