### ISSUE TITLE
 Error verifying developer key: HTTP server returned unexpected status: Not Found 

### ISSUE THREAD

**Issue by Prashneha** [kinow/testlink-java-api#56]
I am getting above error while creating a testlinkapi instance  URL: "http://testlinkb1.firm.msci.org/testlink/lib/api/xmlrpc.php". and testlink version is 1.9.3
could someone help me with the error?

**Comment by kinow** [comment]
Hi, sorry, there have been other issues related to this, and the error was not in the Java code, but in environment settings. 

You can find the old issues searching here in GitHub, e.g. https://github.com/kinow/testlink-java-api/issues?utf8=%E2%9C%93&q=Error+verifying+developer+key
