### ISSUE TITLE
Getting the keyword from Test Case using API

### ISSUE THREAD

**Issue by anishayyoob** [kinow/testlink-java-api#61]
Hi All,

I am trying to get the configured keyword values from the Test Link Test Case. I am able to get the Test Case object using the APIs ,but I am not able to get the key words related to a test case using API.

There is no keyword property in TestCase class.

Please help me to resolve this issue.

Thanks and Regards,
Anish

**Comment by kinow** [comment]
Hi @anishayyoob 

This is not a forum. Keep the issues here for bugs or enhancements.
