### ISSUE TITLE
How to retrieve Attachments for other objects than just TestCases?

### ISSUE THREAD

**Issue by dokaspar** [kinow/testlink-java-api#68]
Hi,

I have two questions regarding attachments:

  1. It seems that with the current testlink-java-api (1.9.14-0) attachments can be uploaded for test cases, test projects, test suites, and executions. However, it's only possible to get them for test cases, they cannot be downloaded for any of the other Testlink objects. Is that true?

  2. Is there any possibility to retrieve an image embedded in a rich-text field? For example, in Testlink you can insert images directly into a TestCase summary, precondition or other rich-text fields. While I'm able to retrieve and decode such fields, they only contain the name of the image file in an HTML element like `<img src="smiley.gif">` and I don't know how download that image through the API. Can you provide any advice on this?

Regards,
Dominik

**Comment by kinow** [comment]
Hi Dominik,

>However, it's only possible to get them for test cases, they cannot be downloaded for any of the other Testlink objects. Is that true?

True.

The Java API simply calls the following PHP function.

https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/4a6bed47e135726cd25351727ffb60487112c4b9/lib/api/xmlrpc/v1/xmlrpc.class.php#L3651

I don't believe there is an equivalent in the XML-RPC API for other entities in TestLink. Might be worth checking the REST API, and if there's no equivalent method there, file an issue in http://mantis.testlink.org requesting that.

>2...Can you provide any advice on this?

There's no method in the API for that, as far as I can tell. And if an issue was filed for that, it would probably be given low priority (or be rejected).

I would try finding the URL (maybe with the web console in the browser, looking at the image URL?), parse the content as you have done to retrieve the image file, and generate the URL myself.

Hope it helps.
Bruno
