### ISSUE TITLE
Error While Integrating TestLink with Maven Pojects

### ISSUE THREAD

**Issue by shabana-parveen** [kinow/testlink-java-api#69]
I am shabana, I tried to integrate TestLink with Selenium webDriver using Maven Framework, I use below dependency, but it showing TestLinkAPIClient symbol doesn't exist. What I observed here is TestLinkAPIClient package is missing from the dependency, 
So to solve the problem I added TestlinkApIClient api dependency inside Plugin then TESTLINKAPICLIENT problem is resolved but now Maven is unable to 
understand WebDriver, Also, When I integrate my framework using TestNG Framwork after downloading full testlinkapiclient package jar, 
execution results successfully updated in Testlink. I went through various site but nothing seem to working.

		<dependency>
			<groupId>org.apache.xmlrpc</groupId>
			<artifactId>xmlrpc-common</artifactId>
			<version>3.1.3</version>
			<type>jar</type>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.xmlrpc</groupId>
			<artifactId>xmlrpc-client</artifactId>
			<version>3.1.3</version>
			<type>jar</type>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>xml-apis</groupId>
			<artifactId>xml-apis</artifactId>
			<version>2.0.2</version>
			<type>jar</type>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>commons-httpclient</groupId>
			<artifactId>commons-httpclient</artifactId> 
			<version>3.1</version>
			<type>jar</type>
			<scope>compile</scope>
		</dependency>
		
 		<dependency>
			<groupId>br.eti.kinoshita</groupId>
				<artifactId>testlink-java-api</artifactId>
				<version>LATEST</version>
		</dependency> 

PS: 
1.     I have created a group on Googlegroup as well but didn't get any reply from any one : https://groups.google.com/forum/#!forum/selenium-webdriver-integration-maven
2.     I have one more question, can I import executed test report through java?, basically do we have any API to import the excuted report through code.
 
Please help me for same ASAP.

**Comment by rafikaranam** [comment]
hi

**Comment by shabana-parveen** [comment]
rafikaranam, hi,

**Comment by rafikaranam** [comment]
can u tell me ur mail id

**Comment by shabana-parveen** [comment]
Shabanaparveen2001@gmail.com<mailto:Shabanaparveen2001@gmail.com>
Skype ID: its_shabanapaveen

Regards
shabana

**Comment by rafikaranam** [comment]
please acept my skype req

**Comment by kinow** [comment]
Hi shabana, 

Your problem seem to be related to your local environment, Java, and the project you are developing. Not really related to the testlink-java-api, or to TestLink.

Marking the ticket as won't fix.

You probably need to check how you are building your project, how to use Maven (or Gradle, or Ivy, if you are more familiar with these tools). Then import the project and use it. Once you have that working, if you have any problems, then please feel free to report issues here.

Thank you
Bruno
