### ISSUE TITLE
Error verifying developer key: HTTP server returned unexpected status: Internal Server Error

### ISSUE THREAD

**Issue by nCodefresh** [kinow/testlink-java-api#77]
I am trying to use testlink-java-api. Locally it works fine, but when i try to run it through jenkins, i get this error: Error verifying developer key: HTTP server returned unexpected status: Internal Server Error
Could you know something about this issue? 
Thanks

**Comment by kinow** [comment]
TL 1.9.15? If so, probably duplicated of #72
