### ISSUE TITLE
Has no function named getTestCaseBugs

### ISSUE THREAD

**Issue by lijie-advantech** [kinow/testlink-java-api#80]
I want get BugID for a testcase

**Comment by kinow** [comment]
Hi @lijie-advantech the Java API is just a façade for a specific version of the TestLink PHP XML-RPC API.

If you need BugID for a testcase, and it is not in the PHP original API for TestLink, it won't be implemented here.

You'd need to check first in the TestLink project where is the BugID for a testcase. In case there are methods to retrieve it that were not implemented, just raise another issue with some description of the operation, TestLink version, etc.
