### ISSUE TITLE
Delete/Update Functionality for TestSuites?

### ISSUE THREAD

**Issue by edorkacerja** [kinow/testlink-java-api#83]
Hello, is there a way to delete a TestSuite using the TestLinkJava API?
I can only see the CREATE_TEST_SUITE method at the TestLinkMethods.java
Thanks a lot!

**Comment by kinow** [comment]
Hi @edorkacerja the API is just a facade for the PHP API, we do not add any additional methods. However, there may be some methods missing.

I never deleted a test suite with the API. Used it mostly to query TestLink and update test cases in Jenkins. Take a look at the PHP API. Should you see a method for deleting test suites, but no equivalent in the Java API, then feel free to file a bug or send a pull request :-)
