### ISSUE TITLE
getTestSuitesForTestPlan() always returns an empty array of TestSuites.

### ISSUE THREAD

**Issue by edorkacerja** [kinow/testlink-java-api#84]
hi, the method TestLinkAPI.getTestSuitesForTestPlan(int testPlanId) always returns an empty array of TestSuites. I tried looking into it but could not find out why.
![testlink](https://cloud.githubusercontent.com/assets/15018483/21396312/74a8bbba-c7a8-11e6-934b-c9e02395655a.PNG)

And I do have TestSuites on my TestPlan 

![testlink2](https://cloud.githubusercontent.com/assets/15018483/21396376/c68dcd62-c7a8-11e6-8381-7619a3fb99a9.PNG)

**Comment by kinow** [comment]
TestLink and API versions?

**Comment by edorkacerja** [comment]
name: 'testlink-java-api', version: '1.9.14-0'

**Comment by jmkraus** [comment]
Regarding your 2nd screenshot: it doesn't show test plan content, but the test specification pool. Are you sure you have a *filled* tplan? Just asking...

Otherwise you might want to use "getFirstLevelTestSuitesForTestProject"

**Comment by edorkacerja** [comment]
@jmkraus  thanks for your reply. I do have a filled testlinkPlan (as you can see in the first picture where I'm debugging)  but there is probably a bug in the code. I haven't figured out how to solve it myself yet.
Your solution works thank you, but the issue should still stay open.

**Comment by kinow** [comment]
Working for TestLink 1.9.19:

```java
        TestSuite[] testSuites = api.getTestSuitesForTestPlan(testPlanId);
        for (TestSuite testsuite : testSuites) {
            System.out.println(testsuite);
        }
```

Result (I have one single :

```
TestSuite [id=2, testProjectId=null, name=Test Suite 1, details=null, parentId=1, order=null, checkDuplicatedName=null, actionOnDuplicatedName=null]
```
