### ISSUE TITLE
Update TestCase always return empty map

### ISSUE THREAD

**Issue by ccupeiro** [kinow/testlink-java-api#85]
Hi!

I'm trying to update the summary of the test case using api.updateTestCase(testCase) function. It's not working well or I'm doing something wrong. I only want to update the Sumary if it has change  but when I call this method the response is [].

Thanks!

**Comment by karmantibi** [comment]
I have a same problem. I would like to update a testCase, but i get back empty response too.

**Comment by abouzy** [comment]
I found out why : in br.eti.kinoshita.testlinkjavaapi.utilUtil getTestCaseMap does not set the test case id (when not null), so update does not work (not only not returning an empty map...). I also suggest to restrict map built to what is provided in the test case, so other stuff will not be involved (same getTestCaseMap)

**Comment by kinow** [comment]
@abouzy if you have a fix that would work with the latest version of TestLink, I'd be happy to review/merge a pull request (:

**Comment by abouzy** [comment]
@kinow done

**Comment by kinow** [comment]
Pull request merged. Releasing 1.9.17-1 in a few hours. Closing. Thanks all for the help and patience.

Bruno
