### ISSUE TITLE
testSuiteId and testProjectId are always null

### ISSUE THREAD

**Issue by vherasme** [kinow/testlink-java-api#87]
When I retrieve the test cases using this:

`TestCase[] tests = api.getTestCasesForTestSuite(sid, Boolean.TRUE, TestCaseDetails.FULL);`

I find that these two properties - **testSuiteId** and **testProjectId**  - are always null. Could you please confirm this ? I want to know if I am making a mistake when retrieving the values. Thanks in advance,

Victor

**Comment by kinow** [comment]
Sure, next time I'm working on the API, will give it a try with the latest PHP version, and see if the XML-RPC response contains these fields 👍

**Comment by kinow** [comment]
Here's the response for `getTestCasesForTestSuite` from the PHP API:

```
{feature_id=4, tcase_name=Test Case 1, tcversion_id=4, external_id=1, exec_on_tplan=5, tcase_id=3, version=1, execution_order=10000, full_external_id=p1-1, exec_id=6, tcversion_number=1, execution_duration=12.00, platform_id=0, platform_name=, exec_status=b, exec_on_build=1, tc_id=3, execution_type=1, id=3, status=7}
```

So the reason for these fields being blank is simply that the API does not return these values for this method. We could add some code to return the suite ID, but we wouldn't have that in other methods that could receive similar treatment. So I prefer to either leave it to be implemented on the client side, or in the PHP code.

Hope that makes sense :+1:
