### ISSUE TITLE
conversion exception

### ISSUE THREAD

**Issue by yvfisch** [kinow/testlink-java-api#89]
Hi!

Could you please give me a hint on what I am doing wrong? I assume it's an error in my code but I don't get what is wrong since I'm using the example on the tutorial page.

I'm using testlink 1.9.16 and the latest api version.

the code

```
        private String DEVKEY="78af5b2c4c3a53a5dc37b883d64e58e7";
	String URL2 = "http://localhost/testlink/lib/api/xmlrpc/v1/xmlrpc.php";
        URL testlinkURL = null;
        
        try     {
                testlinkURL = new URL(URL2);
        } catch ( MalformedURLException mue )   {
                mue.printStackTrace( System.err );
                System.exit(-1);
        }
        
        TestLinkAPI kapi = new TestLinkAPI(testlinkURL, DEVKEY);
```
the last line always causes a conversionException which can not be thrown because of missing ClassDef. 
java.lang.NoClassDefFoundError: org/apache/commons/configuration2/ex/ConversionException

Why is there a conversion exception? 

I would guess it is not the URL since the string to URL conversion is beforehand. And the devkey is provieded by testlink. So why am I getting the exception?

thanks a lot in advance

**Comment by kinow** [comment]
Hi @yvfisch 

Are you using Maven? It looks like some of the Apache Commons Configurations classes were not loaded perhaps?

**Comment by yvfisch** [comment]
Hi kinow!

Thanks a lot for your speedy reply. 

I simply wrote a JUnit Testcase to test the connection to testlink. I don't have Maven, I just run it in Eclipse for now. The resulting jar should be used in SoapUI afterwards with just one reportReport method for the testlink instance and a specific user.

Which external libraries do I need additionally to the testlink-java-api.jar? Is there a collection or something of what I need?

Whenever I add one that is reported missing there's the next one missing...

I have included so far
JUnit 4.12.jar
testlink-api-client-2.0.jar and lib folder (junit, comons-util, xmlrpc-client-3.1)
hamcrest-core-1.3.jar
commons-configuration2-2.1.1.jar
log4j-1.2.17.jar
log4j-api jars
slf4j-api-1.7.25.jar

=> now I get a stackoverflow from the log4j.spi-LoggerRegistry.

thanks a lot

yvfisch

**Comment by nmfernandes** [comment]
I have the same problem.

**Comment by kinow** [comment]
@yvfisch see @nmfernandes comment above. Feel free to re-open in case either 1.9.14-0, or one of the two latest versions, 1.9.17-0 or 1.9.17-1 (just released) also do not work.

Thanks!
Bruno

**Comment by owuraku** [comment]
@kinow I get the same error with version 1.9.17-1
