### ISSUE TITLE
Know if a build is active or not

### ISSUE THREAD

**Issue by kamal951** [kinow/testlink-java-api#91]
Hi, Can you add a method `isActive()` in the class Build. 
Thanks

**Comment by kinow** [comment]
Working on other features and testing the Jenkins plug-in right now @kamal951 Will work on this when triaging issues for future releases. If you would like to see this implemented earlier, feel free to submit a pull request :+1:

**Comment by ranashahan** [comment]
@kinow i can develop simple methods like isActive(), if you please provide me a list of softwares which are required for running smoothly testlink code.

**Comment by kinow** [comment]
Fixed in https://github.com/kinow/testlink-java-api/pull/115 (thanks to @ranashahan), forgot to close this issue.
