### ISSUE TITLE
Retrieve related TestCases

### ISSUE THREAD

**Issue by viictorh** [kinow/testlink-java-api#93]
Hello, first of all, thank you for the API. It's really usefull and it's helping me a lot.

I would like to know if there is any way to get my test cases relatationship, eg: 

To execute test case-10  I need to execute first test case-9 and so on. 
Attached, is the part of TestLink which I need.

Thank you!
![testlink](https://cloud.githubusercontent.com/assets/11792042/25242483/29e3528a-25d0-11e7-9b3e-a384c59a0889.PNG)

**Comment by kinow** [comment]
Hello Victor,

Not sure. Someone needs to check the PHP API. In this Java API, we simply provides a façade for that. So if there is a PHP method, we can add that one here. If not, then open a ticket for TestLink requesting it.

Cheers

**Comment by viictorh** [comment]
Hello, thanks for you reply.

I'll try contact them about it and confirm, but I think they don't have this method.

Thanks.

**Comment by kinow** [comment]
Just keep in mind they have limited developer resources. Ask kindly, explain why you need it, and if you have time and skills, offer to implement it. Otherwise, be understanding if they cannot implement it now.

**Comment by kinow** [comment]
Closing for now. Once they have the method, we can create an equivalent method in this Java API 👍
