### ISSUE TITLE
UpdateTestCase - TestCaseStatus not working

### ISSUE THREAD

**Issue by FilSantos** [kinow/testlink-java-api#98]
When trying to update Status on old version's of TestCase, doesnt work.
	
		URL testlinkURL = new URL("http://testServer/testlink/lib/api/xmlrpc/v1/xmlrpc.php");
		TestLinkAPI api = new TestLinkAPI(testlinkURL, "f6427e53553c8d2ddca411c167653cb1");
		
		String 	projeto = "PDV PALMA",testCaseName = "Test Case",preconditions = "PreConditions", 
				summary = "Summary",tipoTeste = "a", prioridade = "a", revisao = "f";
		
		ExecutionType execution = tipoTeste.toLowerCase().equals("a") ? ExecutionType.AUTOMATED : ExecutionType.MANUAL;
		TestCaseStatus status = revisao.toLowerCase().equals("f") ? TestCaseStatus.FINAL : TestCaseStatus.DRAFT;
		TestImportance importance = prioridade.toLowerCase().equals("a") ? TestImportance.HIGH : prioridade.toLowerCase().equals("m") ? TestImportance.MEDIUM :
									TestImportance.LOW; 
		
		String[] suiteTest = "Vendas".split("\\|");
		
		String actions = "Actions ";
		String expectedResults = "Expected ";
		List<TestCaseStep> steps = new ArrayList<TestCaseStep>();
		for (int passo = 1; passo < 4; passo++) {
			steps.add(new TestCaseStep(null, null, passo, actions + passo, expectedResults , true,execution));
		}

		Integer testProjectId = api.getTestProjectByName(projeto).getId();
		
		TestSuite testSuiteId = null;
		for (int i = 0; i < suiteTest.length; i++) {
			
			boolean localizadoSuite = false;
			TestSuite[] suitesProject = i == 0 ? 	api.getFirstLevelTestSuitesForTestProject(testProjectId) : 
													api.getTestSuitesForTestSuite(testSuiteId.getId());
			for (TestSuite suite : suitesProject) {
				if (suite.getName().toLowerCase().trim().equals(suiteTest[i].toLowerCase().trim())) {
					testSuiteId = suite;
					localizadoSuite = true;
					break;
				}
			}
			
			if (localizadoSuite == false) testSuiteId = api.createTestSuite(testProjectId,suiteTest[i],null
																			,testSuiteId.getId(),null,null,ActionOnDuplicate.GENERATE_NEW);

		}
		
		System.out.println("Verifying existence of test case :" + testCaseName);
		TestCase[] existingTestCases = api.getTestCasesForTestSuite(testSuiteId.getId(), null, null);
		for (TestCase testCaseList : existingTestCases) {
			if (testCaseList.getName().trim().equals(testCaseName)) {
				TestCase testCase = api.getTestCase(testCaseList.getId(), null,null);
				System.out.println("Changing to status obsolete on version " + testCase.getVersion());
				testCase.setTestCaseStatus(TestCaseStatus.OBSOLETE);
				api.updateTestCase(testCase);
				System.out.println("Status of version: " + (testCase.getTestCaseStatus()
						.equals(api.getTestCase(testCase.getId(), null, null).getTestCaseStatus()) ?"updated" : "not updated"));
				
			}
		}

		
		TestCase createTestCase = api.createTestCase(testCaseName, testSuiteId.getId(), testProjectId, "admin", summary, steps, preconditions, status, importance, execution,
											null, null, true, ActionOnDuplicate.CREATE_NEW_VERSION);
		System.out.println("Created ExternalID:" + api.getTestCase( createTestCase.getId(),null, null).getFullExternalId() + 
						   " / Name:" + createTestCase.getName() + " / Version:" + createTestCase.getVersion());

**Comment by kinow** [comment]
Thanks a lot for the code, it was helpful to try understanding the issue. It worked with 1.9.19, and the latest code (to be released today or tomorrow).

Here's a screenshot. Previous version was Draft. Then running your example (modified project name, test name, api key, etc), a new version was created with Final, and the previous version was marked as Obsolete.

![Screen Shot 2019-04-22 at 20 58 15-fullpage](https://user-images.githubusercontent.com/304786/56492973-947cd780-6541-11e9-98e9-ca3a18ee63fe.png)
