### ISSUE TITLE
Retrieve time related TestCases

### ISSUE THREAD

**Issue by tuananhvi** [kinow/testlink-java-api#99]
Hello, thank you for the API. It's really usefull and it's helping me a lot.

I would like to know if there is any way to get time created of test case ?(or time assigned of test case)

**Comment by kinow** [comment]
Hi, thanks!

It depends if the TestLink PHP API returns this data. If it does, then we are either returning it too, or need to work on an enhancement to do so, and then cut a new release.

Someone would need to investigate these possibilities and report back. I'm busy with other projects right now, so it'll take a while. But if anybody else is up for it, I'd be happy to review / merge pull requests and release it.

**Comment by tuananhnguyen2592** [comment]
Hello, thanks for you reply.

i'm checked it. I think the TestLink PHP API not returns this data(may be i were wrong).

Thanks.

**Comment by kinow** [comment]
If that's the case, we'd need a ticket there first. Then some work around it. And once it's released, we'd need to release a new version of this API.
